notifications:
  email: false

sudo: false
dist: trusty

language: c
compiler: gcc
cache: ccache

git:
  depth: 3

before_script:
  - export -f travis_nanoseconds
  - export -f travis_fold
  - export -f travis_time_start
  - export -f travis_time_finish

script:
  - ./test.sh

